import React from 'react';
import {
    FolderOutlined,
    FileOutlined,
    TeamOutlined,
    UserOutlined,
    BarChartOutlined,
    PieChartOutlined,
    LineChartOutlined,
    DollarOutlined,
    BankOutlined,
    SafetyOutlined,
    AuditOutlined,
    FileTextOutlined,
    FilePdfOutlined,
    BookOutlined,
    DatabaseOutlined,
    CloudOutlined,
    LockOutlined,
    GlobalOutlined,
    ShopOutlined,
    SettingOutlined,
    ToolOutlined,
    ExperimentOutlined,
    BulbOutlined,
    StarOutlined,
    HeartOutlined,
    ThunderboltOutlined,
    RocketOutlined,
    CrownOutlined,
    TrophyOutlined,
    CalendarOutlined,
    ClockCircleOutlined,
    MailOutlined,
    MessageOutlined,
    CheckCircleOutlined,
    FlagOutlined,
    TagOutlined,
    AppstoreOutlined,
    LayoutOutlined,
    ProjectOutlined,
    SolutionOutlined,
    ProfileOutlined,
    ContainerOutlined,
    InboxOutlined,
    FundOutlined,
    StockOutlined,
    AccountBookOutlined,
    WalletOutlined,
    InsuranceOutlined,
    PropertySafetyOutlined,
    ReconciliationOutlined,
    SnippetsOutlined,
    CarryOutOutlined,
    ScheduleOutlined,
    SearchOutlined,
    CalculatorOutlined,
} from '@ant-design/icons';

// Icon name to component mapping
export const spaceIconMap: Record<string, React.ComponentType<{ style?: React.CSSProperties }>> = {
    folder: FolderOutlined,
    file: FileOutlined,
    team: TeamOutlined,
    user: UserOutlined,
    'bar-chart': BarChartOutlined,
    'pie-chart': PieChartOutlined,
    'line-chart': LineChartOutlined,
    dollar: DollarOutlined,
    bank: BankOutlined,
    safety: SafetyOutlined,
    audit: AuditOutlined,
    'file-text': FileTextOutlined,
    'file-pdf': FilePdfOutlined,
    book: BookOutlined,
    database: DatabaseOutlined,
    cloud: CloudOutlined,
    lock: LockOutlined,
    global: GlobalOutlined,
    shop: ShopOutlined,
    setting: SettingOutlined,
    tool: ToolOutlined,
    experiment: ExperimentOutlined,
    bulb: BulbOutlined,
    star: StarOutlined,
    heart: HeartOutlined,
    thunderbolt: ThunderboltOutlined,
    rocket: RocketOutlined,
    crown: CrownOutlined,
    trophy: TrophyOutlined,
    calendar: CalendarOutlined,
    clock: ClockCircleOutlined,
    mail: MailOutlined,
    message: MessageOutlined,
    'check-circle': CheckCircleOutlined,
    flag: FlagOutlined,
    tag: TagOutlined,
    appstore: AppstoreOutlined,
    layout: LayoutOutlined,
    project: ProjectOutlined,
    solution: SolutionOutlined,
    profile: ProfileOutlined,
    container: ContainerOutlined,
    inbox: InboxOutlined,
    fund: FundOutlined,
    stock: StockOutlined,
    'account-book': AccountBookOutlined,
    wallet: WalletOutlined,
    insurance: InsuranceOutlined,
    'property-safety': PropertySafetyOutlined,
    reconciliation: ReconciliationOutlined,
    snippets: SnippetsOutlined,
    'carry-out': CarryOutOutlined,
    schedule: ScheduleOutlined,
    search: SearchOutlined,
    calculator: CalculatorOutlined,
    read: FileTextOutlined,
    warning: SafetyOutlined,
    robot: SettingOutlined,
    api: CloudOutlined,
};

// Categorized icons for the picker
export const iconCategories = {
    'Business': ['bank', 'dollar', 'fund', 'stock', 'account-book', 'wallet', 'insurance', 'shop'],
    'Documents': ['file', 'file-text', 'file-pdf', 'book', 'snippets', 'profile', 'solution', 'reconciliation'],
    'Charts': ['bar-chart', 'pie-chart', 'line-chart'],
    'Organization': ['team', 'user', 'crown', 'trophy'],
    'Compliance': ['safety', 'audit', 'lock', 'property-safety', 'check-circle'],
    'Planning': ['calendar', 'clock', 'schedule', 'carry-out', 'project', 'flag'],
    'Storage': ['folder', 'database', 'cloud', 'container', 'inbox'],
    'General': ['star', 'heart', 'bulb', 'rocket', 'thunderbolt', 'tag', 'appstore'],
};

// Get all icon names as flat array
export const allIconNames = Object.keys(spaceIconMap);

interface SpaceIconProps {
    icon: string;
    style?: React.CSSProperties;
}

export const SpaceIcon: React.FC<SpaceIconProps> = ({ icon, style }) => {
    const IconComponent = spaceIconMap[icon] || FolderOutlined;
    return <IconComponent style={style} />;
};

export default SpaceIcon;
