"""Default agent registry rows (kept in sync with sql/01_schema.sql seed)."""

from __future__ import annotations

from copy import deepcopy
from typing import Any

# Canonical seed used by MemoryStore and as documentation for SQL seed.
# All agents are MCP endpoints. Locals use localhost mcp_url + local_module
# (in-process load avoids self-HTTP deadlock); remotes have mcp_url only.
DEFAULT_AGENTS: list[dict[str, Any]] = [
    {
        "id": "search",
        "name": "Perplexity",
        "description": "Web search via Perplexity (docs & current info)",
        "enabled": True,
        "sort_order": 10,
        "auth": "env_api_key",
        "mcp_url": "http://127.0.0.1:8000/mcp/search",
        "local_module": "search",
        "skill_id": "search",
        "scopes": [],
        "env_keys": ["PERPLEXITY_API_KEY"],
        "oauth_authorize_url": None,
        "oauth_token_url": None,
        "oauth_registration_url": None,
        "oauth_revocation_url": None,
        "client_id_env": None,
        "client_secret_env": None,
        "metadata": {},
    },
    {
        "id": "calculator",
        "name": "Calculator",
        "description": "Math and expression evaluation",
        "enabled": True,
        "sort_order": 20,
        "auth": "none",
        "mcp_url": "http://127.0.0.1:8000/mcp/calculator",
        "local_module": "calculator",
        "skill_id": "calculator",
        "scopes": [],
        "env_keys": [],
        "oauth_authorize_url": None,
        "oauth_token_url": None,
        "oauth_registration_url": None,
        "oauth_revocation_url": None,
        "client_id_env": None,
        "client_secret_env": None,
        "metadata": {},
    },
    {
        "id": "weather",
        "name": "Weather",
        "description": "Current weather for a city",
        "enabled": True,
        "sort_order": 30,
        "auth": "none",
        "mcp_url": "http://127.0.0.1:8000/mcp/weather",
        "local_module": "weather",
        "skill_id": "weather",
        "scopes": [],
        "env_keys": [],
        "oauth_authorize_url": None,
        "oauth_token_url": None,
        "oauth_registration_url": None,
        "oauth_revocation_url": None,
        "client_id_env": None,
        "client_secret_env": None,
        "metadata": {},
    },
    {
        "id": "datetime",
        "name": "Date & Time",
        "description": "Current date/time and simple conversions",
        "enabled": True,
        "sort_order": 40,
        "auth": "none",
        "mcp_url": "http://127.0.0.1:8000/mcp/datetime",
        "local_module": "datetime",
        "skill_id": "datetime",
        "scopes": [],
        "env_keys": [],
        "oauth_authorize_url": None,
        "oauth_token_url": None,
        "oauth_registration_url": None,
        "oauth_revocation_url": None,
        "client_id_env": None,
        "client_secret_env": None,
        "metadata": {},
    },
    {
        "id": "linear",
        "name": "Linear",
        "description": "Issues, projects, and comments (read-only)",
        "enabled": True,
        "sort_order": 50,
        "auth": "oauth_dcr",
        "mcp_url": "https://mcp.linear.app/mcp/readonly",
        "local_module": None,
        "skill_id": "linear",
        "scopes": ["read"],
        "env_keys": [],
        "oauth_authorize_url": "https://mcp.linear.app/authorize",
        "oauth_token_url": "https://mcp.linear.app/token",
        "oauth_registration_url": "https://mcp.linear.app/register",
        "oauth_revocation_url": "https://mcp.linear.app/token",
        "client_id_env": None,
        "client_secret_env": None,
        "metadata": {},
    },
]


def default_agents() -> list[dict[str, Any]]:
    return deepcopy(DEFAULT_AGENTS)
